behaviors:
  FoodAgent:
    trainer_type: ppo
    max_steps: 1000000
    time_horizon: 64
    checkpoint_interval: 50000
    keep_checkpoints: 5
    summary_freq: 5000
    hyperparameters:
      batch_size: 128
      buffer_size: 2048
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      num_layers: 2
      hidden_units: 128
      normalize: true
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
